# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO cmazakas/unordered
    REF 3c4c3a0007c673c2d72972422592bc9b1354f7a2
    SHA512 255ffc180a5dc8fa28cb65c591dc5cf07f3fe50ec3e46833d459a1229276cfe2c20dc7233332c3ae45974c61e67a6c080f1a6cf2aa799291bbfa73bae366154d
    HEAD_REF vcpkg-test
)

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
